// Generated by HyperSpeed build-plan generator (#319).
//
// Shared ROOT vitest config — pre-seeded onto the base branch so every parallel
// Phase-0 session branches from a base that already has it. Without a seeded
// config every TS/vitest session recreates this file in its own worktree (only
// one owns it per the manifest) → an add/add merge conflict at Wave 0 that halts
// the whole build before any feature work. Keep it minimal: the glob-based
// vitest.workspace.ts selects which files run; this root config only carries
// shared defaults. Phase 0 owns it; feature sessions never edit it.
import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    environment: 'node',
  },
});
