// Generated by HyperSpeed build-plan generator (#136 defect 8 / #320).
//
// GLOB-BASED test workspace — DO NOT add per-session entries. Feature sessions
// drop their test files where the `include` globs below already match (session-
// scoped `tests/<id>.test.ts`, `src/**/*.test.ts`, and `tests/integration/**`);
// they must never edit this file. A per-session-entry workspace is a shared
// registry every session in a wave appends to, which the runner's dependency-only
// reconcile cannot union-merge → fatal same-wave conflicts. Phase 0 owns it, and
// the runner seeds it onto the base branch so no session re-authors it (#320).
//
// NOTE: a vitest workspace is a list of PROJECTS, so a bare glob of test FILES
// (e.g. 'tests/**/*.test.ts') is invalid — vitest would try to load each matched
// test file as a project config ("failed to load config"). The correct shape is
// an inline project whose `test.include` globs the test files.
import { defineWorkspace } from 'vitest/config';

export default defineWorkspace([
  {
    test: {
      name: 'app',
      environment: 'node',
      include: [
        'src/**/*.test.ts',
        'tests/**/*.test.ts',
        'tests/**/*.spec.ts',
      ],
    },
  },
]);
