// Generated by HyperSpeed build-plan generator (#320).
//
// DIRECTORY-SCAN route auto-discovery for a framework-free node:http server. The
// backend twin of the #188 frontend routes.tsx glob. Pre-seeded onto the base
// branch and owned by Phase 0 — feature sessions NEVER edit this file. A feature
// session registers routes purely by CREATING a module under ./ (e.g.
// src/routes/todos.ts) that default-exports an array of Route; loadRoutes()
// discovers and returns them all. A hand-maintained route index would be a shared
// registry every backend session appends to — the very orphaned-route conflict
// (#320) this replaces.
import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import type { Route } from '../http.js';

const here = path.dirname(fileURLToPath(import.meta.url));

/** Discover every route module under ./ and return the union of their exported
*  Route[]. Async (dynamic import) and called from createServer() — there is
*  deliberately NO top-level await here, so importing this module can never
*  deadlock under native node ("unsettled top-level await"). Tolerant: a module
*  that fails to import, or whose default export is not a Route[], is skipped
*  rather than crashing discovery. */
export async function loadRoutes(): Promise<Route[]> {
  let rels: string[] = [];
  try {
    rels = fs
      .readdirSync(here, { recursive: true, withFileTypes: true })
      .filter((d) => d.isFile())
      .map((d) => path.relative(here, path.join((d as fs.Dirent).parentPath ?? here, d.name)))
      .filter((rel) => /\.[cm]?[jt]s$/.test(rel))                 // js/ts modules only
      .filter((rel) => !/(^|\/)index\.[cm]?[jt]s$/.test(rel))    // never re-import this registry
      .filter((rel) => !/(^|\/)_/.test(rel))                       // _private modules are not routes
      .filter((rel) => !/\.(test|spec)\.[cm]?[jt]s$/.test(rel))   // tests are not routes
      .sort();                                                       // deterministic order
  } catch {
    return [];
  }

  const routes: Route[] = [];
  for (const rel of rels) {
    let mod: Record<string, unknown>;
    try {
      mod = (await import(pathToFileURL(path.join(here, rel)).href)) as Record<string, unknown>;
    } catch {
      continue; // a non-importable sibling never crashes discovery
    }
    const exported = (mod.default ?? (mod as { routes?: unknown }).routes);
    const list = Array.isArray(exported) ? exported : [];
    for (const r of list) {
      const route = r as Route;
      if (route && typeof route.method === 'string' && typeof route.path === 'string'
          && typeof route.handler === 'function') {
        routes.push(route);
      }
    }
  }
  return routes;
}
