// Generated by HyperSpeed build-plan generator (#320).
//
// The ONE canonical server. Pre-seeded onto the base branch and owned by Phase 0
// — feature sessions NEVER edit it. createServer() auto-discovers every route
// module (see ./routes/index.ts) and dispatches by method + path; an unknown
// route returns 404 JSON. Routes mount themselves by being discovered, so no
// session edits this file to register a route (the #320 fix). This resolves the
// historical duplicate-server confusion: this is the single entry the process
// (src/server.ts) and the boot-and-hit gate both use.
import http from 'node:http';
import { loadRoutes } from './routes/index.js';
import { compileRoute, matchPath, readJsonBody, sendJson, type RouteRequest } from './http.js';

/** Build (but do not start) the HTTP server with all discovered routes mounted.
*  Async because route discovery uses dynamic import. Call `.listen(port)` on the
*  returned server — the entry (src/server.ts) does this; tests listen on port 0. */
export async function createServer(): Promise<http.Server> {
  const routes = await loadRoutes();
  const compiled = routes.map((r) => ({ r, c: compileRoute(r.path) }));

  return http.createServer(async (req, res) => {
    try {
      const method = (req.method ?? 'GET').toUpperCase();
      const pathname = new URL(req.url ?? '/', 'http://localhost').pathname;
      // #329: boot-gate identity probe. When HS_BOOT_TOKEN is set (only the
      // boot-and-hit gate does this), echo it at GET /__boot so the gate can PROVE
      // the listener it reached is THIS server — not a stale/foreign squatter on
      // the port. Inert (route never exists) in normal runs where the env is unset.
      if (process.env.HS_BOOT_TOKEN && method === 'GET' && pathname === '/__boot') {
        sendJson(res, 200, { token: process.env.HS_BOOT_TOKEN });
        return;
      }
      const body = method === 'GET' || method === 'HEAD' ? undefined : await readJsonBody(req);
      for (const { r, c } of compiled) {
        if (r.method.toUpperCase() !== method) continue;
        const params = matchPath(c, pathname);
        if (!params) continue;
        const rq = req as RouteRequest;
        rq.params = params;
        rq.body = body;
        await r.handler(rq, res);
        return;
      }
      sendJson(res, 404, { error: 'Route not found' });
    } catch {
      if (!res.headersSent) sendJson(res, 500, { error: 'Internal Server Error' });
      else res.end();
    }
  });
}
