// Generated by HyperSpeed build-plan generator (#320).
//
// Framework-free node:http helpers + the route-module contract. Pre-seeded onto
// the base branch (like tsconfig.json) and owned by Phase 0 — feature sessions
// NEVER edit this file. A feature route module under src/routes/ default-exports
// an array of `Route`; src/routes/index.ts auto-discovers it and src/app.ts
// dispatches to its handler. Handlers read `req.body` (parsed JSON) + `req.params`
// and reply via `sendJson(res, status, data)`.
import type { IncomingMessage, ServerResponse } from 'node:http';

export interface RouteRequest extends IncomingMessage {
  /** Parsed JSON request body (undefined when absent or unparseable). */
  body?: unknown;
  /** Path parameters captured from the route pattern, e.g. { id: "42" }. */
  params: Record<string, string>;
}

export type RouteHandler = (req: RouteRequest, res: ServerResponse) => void | Promise<void>;

export interface Route {
  /** HTTP method (case-insensitive): "GET", "POST", "PATCH", … */
  method: string;
  /** Express-style path with :params, e.g. "/todos/:id/toggle". */
  path: string;
  handler: RouteHandler;
}

/** Write a JSON response with the given status code. */
export function sendJson(res: ServerResponse, status: number, data: unknown): void {
  res.writeHead(status, { 'content-type': 'application/json' });
  res.end(JSON.stringify(data));
}

/** Read + JSON-parse the request body. Resolves undefined for an empty or
*  malformed body; never throws. */
export function readJsonBody(req: IncomingMessage): Promise<unknown> {
  return new Promise((resolve) => {
    const chunks: Buffer[] = [];
    req.on('data', (c) => chunks.push(c as Buffer));
    req.on('end', () => {
      const raw = Buffer.concat(chunks).toString('utf-8').trim();
      if (!raw) return resolve(undefined);
      try { resolve(JSON.parse(raw)); } catch { resolve(undefined); }
    });
    req.on('error', () => resolve(undefined));
  });
}

/** A compiled route path — its non-empty segments (":id" segments are params). */
export interface CompiledRoute { segments: string[] }

/** Split an Express-style path ("/todos/:id/toggle") into matchable segments.
*  Segment-based matching avoids regex-metachar escaping entirely. */
export function compileRoute(routePath: string): CompiledRoute {
  return { segments: routePath.split('/').filter(Boolean) };
}

/** Match a pathname against a compiled route → captured params, or null. Segment
*  counts must match exactly; a ":name" segment captures any single segment. */
export function matchPath(compiled: CompiledRoute, pathname: string): Record<string, string> | null {
  const parts = pathname.split('/').filter(Boolean);
  if (parts.length !== compiled.segments.length) return null;
  const params: Record<string, string> = {};
  for (let i = 0; i < compiled.segments.length; i++) {
    const seg = compiled.segments[i];
    if (seg.startsWith(':')) { params[seg.slice(1)] = decodeURIComponent(parts[i]); continue; }
    if (seg !== parts[i]) return null;
  }
  return params;
}
