// Generated by HyperSpeed build-plan generator (#320).
//
// Process entry: build the canonical server (src/app.ts) and listen. Pre-seeded
// onto the base branch and owned by Phase 0 — feature sessions NEVER edit it. No
// top-level await (uses .then) so native node never reports "unsettled top-level
// await". PORT defaults to 3000; the boot-and-hit gate overrides it via env.
import { createServer } from './app.js';

const port = Number(process.env.PORT) || 3000;
createServer()
  .then((server) => {
    // Fail FAST + LOUD on a bind error (e.g. EADDRINUSE) instead of leaving the
    // port to a stale server: exit non-zero so a supervisor/boot-gate sees the
    // process die rather than silently probing whatever else holds the port.
    server.on('error', (err) => {
      // eslint-disable-next-line no-console
      console.error('server failed to bind', err);
      process.exit(1);
    });
    server.listen(port, () => {
      // eslint-disable-next-line no-console
      console.log(`server listening on http://localhost:${port}`);
    });
  })
  .catch((err) => {
    // eslint-disable-next-line no-console
    console.error('failed to start server', err);
    process.exit(1);
  });
